insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000001', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000002', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000003', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000004', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000005', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000006', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000007', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000008', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000009', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000010', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000011', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000012', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000013', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000014', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000015', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000016', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000017', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000018', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000019', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000020', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000021', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000022', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000023', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000024', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000025', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000026', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000027', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000028', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000029', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');
insert into tabela1 (id_literal, campo1, campo2, campo3) 
values ('IMD0000030', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 
'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO', 'VAMOS POPULAR ESSA TABELA COM MUITO TEXTO');